apiVersion: v1
kind: Service
metadata:
  name: guestbook-deployment-service
  labels:
    name: guestbook-deployment-service
    app: demo-guestbook-app
spec:
  selector:
    type: LoadBalancer
    name: guestbook-deployment
    app: demo-guestbook-app
  ports:
  - port: 80
    targetPort: 80


